local map = vim.keymap.set

map('n', '<leader>ws', ':split<CR>', { noremap = true, silent = true, desc = 'Split horizontally' })
map('n', '<leader>wv', ':vsplit<CR>', { noremap = true, silent = true, desc = 'Split vertically' })
map('n', '<leader>wq', ':q<CR>', { noremap = true, silent = true, desc = 'Close Window' })
map('n', '<leader>wl', '<C-w>l', { noremap = true, silent = true, desc = 'To Window on the left' })
map('n', '<leader>wk', '<C-w>k', { noremap = true, silent = true, desc = 'To Window on the top' })
map('n', '<leader>wj', '<C-w>j', { noremap = true, silent = true, desc = 'To Window on the bottom' })
map('n', '<leader>wh', '<C-w>h', { noremap = true, silent = true, desc = 'To Window on the right' })
map('n', '<leader>w[', '<cmd>res-1<cr>', { noremap = true, silent = true, desc = 'Resize - 1' })
map('n', '<leader>w]', '<cmd>res+1<cr>', { noremap = true, silent = true, desc = 'Resize + 1' })
map('n', '<leader>j', '10j', { noremap = true, silent = true })
map('n', '<leader>k', '10k', { noremap = true, silent = true })
map('n', '<leader>h', '^', { noremap = true, silent = true })
map('n', '<leader>l', '$', { noremap = true, silent = true })
map('n', 'gY', ':%y+<CR>', { noremap = true, silent = true, desc = 'Yank entire file' })
map('n', '<Esc>', '<cmd>nohlsearch<CR>')
map('i', 'jj', '<ESC>')
map('t', '<Esc><Esc>', '<C-><C-n>', { desc = 'Exit terminal mode' })
map('n', '<C-h>', '<C-w><C-h>', { desc = 'Move focus to the left window' })
map('n', '<C-l>', '<C-w><C-l>', { desc = 'Move focus to the right window' })
map('n', '<C-j>', '<C-w><C-j>', { desc = 'Move focus to the lower window' })
map('n', '<C-k>', '<C-w><C-k>', { desc = 'Move focus to the upper window' })
map('n', '<leader>=', '<cmd>w<CR>', { desc = 'Save', silent = true })
map('n', '<leader>bc', '<cmd>%bd|e#<CR>', { desc = 'Delete all buffers but last one' })
map('n', '<leader>bd', '<cmd>bd<CR>', { desc = 'Delete buffer' })
map('n', '<leader>b', '<cmd>buffer #<cr>')
